version: '3'
services:
  irbtc-wss.test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-8080}:8080'
    env_file: .env
    environment:
      - NODE_ENV=development
      - REDIS_URL=${REDIS_CONNECTION_URL}
    volumes:
      - '.:/wss'
    networks:
      - wss_network
    depends_on:
      - redis
    restart: always
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - './storage/dbdata/redis:/data'
    networks:
      - wss_network
    restart: always
networks:
  wss_network:
    driver: bridge
volumes:
  wss-redis:
    driver: local